version: "3"

services:
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - fluentd
        networks:
            - graylog

    fluentd:
        build: ./fluentd
        ports:
            - "5140:5140/udp"
        volumes:
            - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
        depends_on:
            - kafka
        networks:
            - graylog

    kafka:
        image: confluentinc/cp-kafka:7.3.2
        ports:
            - "9092:9092"
            - "29092:29092"
            - "9999:9999"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_JMX_PORT: 9999
            KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
        depends_on:
            - zookeeper
        networks:
            - graylog

    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_SERVERS: zookeeper:2888:3888
        networks:
            - graylog

    mongodb:
        image: mongo:6.0
        networks:
            - graylog
        volumes:
            - mongo_data:/data/db

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        networks:
            - graylog

    graylog:
        image: graylog/graylog:5.1
        volumes:
            - graylog_journal:/usr/share/graylog/data/journal
        environment:
            - GRAYLOG_PASSWORD_SECRET=nguyenconglucgroup11
            - GRAYLOG_ROOT_PASSWORD_SHA2=1b3353fb3deb4e3bf48c854c69a19976ae6d2d3ced74ab681dcc7deb09e6c49b
            - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.75:9000/
            - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
        networks:
            - graylog
        depends_on:
            - mongodb
            - elasticsearch
            - kafka
            - zookeeper
        ports:
            - "9000:9000"
            - "1514:1514"
            - "1514:1514/udp"
            - "12201:12201"
            - "12201:12201/udp"

networks:
    graylog:
        driver: bridge

volumes:
    mongo_data:
        driver: local
    es_data:
        driver: local
    graylog_journal:
        driver: local
